name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv\Scripts\python -m pip install --upgrade pip wheel setuptools
          venv\Scripts\python -m pip install aiohttp

      - name: Build Style
        run: |
          python build/style.py

      - name: Build Web
        run: |
          npm install
          npm run build

      - name: Publish
        env:
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\python build/upload.py
